<ul class="main-nav">
    <li><a href="index.php">Home</a></li>
    <li><a href="about.php">About</a></li>
    <li><a href="part-gallery.php">Parts Gallery</a></li>
    <li><a href="equipment-list.php">Equipment List</a></li>
    <li><a href="quality.php">Quality</a></li>
    <li><a href="contact.php">Contact</a></li>
</ul>
<span>Copyright &copy; all rights reserved.
    <script type="text/javascript">
        var d = new Date()
        document.write(d.getFullYear())
    </script></span>